### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by Bek81** [jeresig/node-pastec#1]
Hi,

I tried to install this package to test pastec in a node app.
I got some problem:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install', 'node-pastec', '--save' ]
2 info using npm@2.5.0
3 info using node@v0.12.0
4 verbose node symlink /usr/bin/node
5 warn package.json TEST@1.0.0 No description
6 warn package.json TEST@1.0.0 No repository field.
7 warn package.json TEST@1.0.0 No README data
8 silly cache add args [ 'node-pastec', null ]
9 verbose cache add spec node-pastec
10 silly cache add parsed spec { raw: 'node-pastec',
10 silly cache add   scope: null,
10 silly cache add   name: 'node-pastec',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '_',
10 silly cache add   type: 'range' }
11 verbose addNamed node-pastec@_
12 silly addNamed semver.valid null
13 silly addNamed semver.validRange *
14 silly addNameRange { name: 'node-pastec', range: '*', hasData: false }
15 silly mapToRegistry name node-pastec
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/node-pastec
19 verbose addNameRange registry:https://registry.npmjs.org/node-pastec not in flight; fetching
20 verbose request uri https://registry.npmjs.org/node-pastec
21 verbose request no auth needed
22 info attempt registry request try #1 at 17:20:29
23 verbose request id 8a14be4202211ba2
24 http request GET https://registry.npmjs.org/node-pastec
25 http 404 https://registry.npmjs.org/node-pastec
26 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 verbose headers   'content-type': 'application/json',
26 verbose headers   'cache-control': 'max-age=0',
26 verbose headers   'content-length': '51',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Wed, 20 May 2015 15:20:29 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   age: '0',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-fra1222-FRA',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1432135229.569734,VS0,VE180' }
27 silly get cb [ 404,
27 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
27 silly get     'content-type': 'application/json',
27 silly get     'cache-control': 'max-age=0',
27 silly get     'content-length': '51',
27 silly get     'accept-ranges': 'bytes',
27 silly get     date: 'Wed, 20 May 2015 15:20:29 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     age: '0',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-fra1222-FRA',
27 silly get     'x-cache': 'MISS',
27 silly get     'x-cache-hits': '0',
27 silly get     'x-timer': 'S1432135229.569734,VS0,VE180' } ]
28 verbose stack Error: 404 Not Found: node-pastec
28 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:14)
28 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
28 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:373:22)
28 verbose stack     at Request.emit (events.js:110:17)
28 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1318:14)
28 verbose stack     at Request.emit (events.js:129:20)
28 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1266:12)
28 verbose stack     at IncomingMessage.emit (events.js:129:20)
28 verbose stack     at _stream_readable.js:908:16
28 verbose stack     at process._tickCallback (node.js:355:11)
29 verbose statusCode 404
30 verbose pkgid node-pastec
31 verbose cwd /Users/beki/Documents/_sviluppo/_node/vari_test/vinyl
32 error Darwin 13.4.0
33 error argv "node" "/usr/bin/npm" "install" "node-pastec" "--save"
34 error node v0.12.0
35 error npm  v2.5.0
36 error code E404
37 error 404 Not Found: node-pastec
37 error 404
37 error 404 'node-pastec' is not in the npm registry.
37 error 404 You should bug the author to publish it (or use the name yourself!)
37 error 404 It was specified as a dependency of 'TEST'
37 error 404
37 error 404 Note that you can also install from a
37 error 404 tarball, folder, http url, or git url.
38 verbose exit [ 1, true ]

Thank you in advance and regards.

**Comment by jeresig** [comment]
@Bek81 Sorry for the confusion and delay in getting back to you! The name of the package on `npm` is just `paste`. Hope that helps!
